= Data Quality Concepts (DQC)
:edition: 1.1.0
:revdate: 2010-02-26

== Data Quality Concepts (DQC) Version 1.2.0

=== Description

Data Quality Concepts (DQC) is an XML Schema implementation of abstract classes for
ISO 19157, Geographic Information - Data Quality. It includes elements for defining
geometry and functions for coverages. The XML schema was encoded using the encoding
rules defined in ISO 19118, ISO 19139.

=== XML Namespace for Data Quality Concepts (DQC) Version: 1.2

The namespace URI for Data Quality [abstract classes] (DQC) Version 1.2.0 is
*https://schemas.isotc211.org/19157/-/dqc/1.2*.

=== XML Schema for Data Quality Concepts (DQC) Version 1.2.0

*link:../../../../19157/-/dqc/1.2.0/dqc.xsd[dqc.xsd]* is the XML Schema document to
be referenced by XML documents containing XML elements in the dqc namespace or by XML
Schema documents importing the dqc 1.2 namespace. This XML schema includes
(indirectly) all the implemented concepts of the dqc namespace, but it does not
contain the declaration of any types.

=== Related XML Schema for dqc 1.2

*link:../../../../19157/-/dqc/1.2.0/abstract.xsd[https://schemas.isotc211.org/19157/-/dqc/1.2.0/abstract.xsd]*
implements the UML conceptual schema defined in ISO 19157, Geographic Information -
Data Quality. It was created using the encoding rules defined in ISO 19118, ISO 19139.

https://schemas.isotc211.org/19157/-/dqc/1.2.0/abstract.xsd[https://schemas.isotc211.org/19157/-/dqc/1.2.0/abstract.xsd] contains the following classes:

* Abstract_DataQuality
* Abstract_QualityElement

=== Related XML Namespaces for ISO 19157 DQC 1.2

The DQC 1.2.0 imports these other namespaces:

[%unnumbered]
[options=header,cols=4]
|===
| Name | Standard Prefix | Namespace Location | Schema Location

| Geographic Common Objects | gco |
https://schemas.isotc211.org/19103/-/gco/1.2.0[https://schemas.isotc211.org/19103/-/gco/1.2] | ../../../../19103/-/gco/1.2.0/gco.xsd
|===

=== Working Versions

When revisions to these schema become necessary, they will be managed in the
https://github.com/ISO-TC211/XML[ISO TC211 Git Repository].
