name: build

on:
  push:
    branches: [ main, staging ]
  pull_request:

jobs:
  build:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Setup prerequisites
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y curl make libxml2-dev libxslt-dev libnode-dev node-gyp libssl-dev npm openssl xsltproc
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Update schemas.yml and build documentation
        run: |
          # Set cache directory to a location in the runner's workspace
          export HRMA_CACHE_DIR=$GITHUB_WORKSPACE/.hrma-cache

          # Update schemas manifest
          bundle exec hrma schemas manifest update

          # Build documentation
          bundle exec hrma build documentation
