name: build

on:
  push:
    branches: [ main, staging ]
  pull_request:

jobs:
  build:
    name: Generate XSD documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev libnode-dev node-gyp libssl-dev npm openssl xsltproc
      - name: Setup snaps
        run: |
          sudo snap install yq
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Install dependencies
        run: |
          bundle install
      - name: Update schemas.yml
        run: |
          ./bin/hrma schemas manifest update
      - name: Build XSD documentation
        run: |
          make _xsddoc
